config/routes.rb
Rails.application.routes.draw do
  resources :credit_cards
 
  devise_for :users
 
  resources :products
  resources :charges
  get 'charges/:id/paypal_payment', to: 'charges#paypal_payment', as: 'paypal_payment'
  match '/paypal_action' => 'charges#paypal_action', via: [:get, :post], as: 'paypal_action'
  match '/payu_callback' => 'charges#payu_return', via: [:get, :post], as: 'payments_payu_return'

  mount StripeEvent::Engine, at: '/payments'
  root to: 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :set_credit_card, only: [:show, :edit, :update, :destroy]

  # GET /credit_cards
  # GET /credit_cards.json
  def index
    @credit_cards = CreditCard.all
  end

  # GET /credit_cards/1
  # GET /credit_cards/1.json
  def show
  end

  # GET /credit_cards/new
  def new
    @credit_card = CreditCard.new
  end

  # GET /credit_cards/1/edit
  def edit
  end

  # POST /credit_cards
  # POST /credit_cards.json
  def create
    @credit_card = CreditCard.new(credit_card_params)

    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully created.' }
        format.json { render :show, status: :created, location: @credit_card }
      else
        format.html { render :new }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credit_cards/1
  # PATCH/PUT /credit_cards/1.json
  def update
    respond_to do |format|
      if @credit_card.update(credit_card_params)
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit_card }
      else
        format.html { render :edit }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_cards/1
  # DELETE /credit_cards/1.json
  def destroy
    @credit_card.destroy
    respond_to do |format|
      format.html { redirect_to credit_cards_url, notice: 'Credit card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_card
      @credit_card = CreditCard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def credit_card_params
      params.require(:credit_card).permit(:digits, :cvc, :month, :year, :user_id)
    end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_form.html.erb
<%= form_with(model: credit_card, local: true) do |form| %>
  <% if credit_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h2>

      <ul>
      <% credit_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :digits %>
    <%= form.text_field :digits %>
  </div>

  <div class="field">
    <%= form.label :cvc %>
    <%= form.number_field :cvc %>
  </div>

  <div class="field">
    <%= form.label :month %>
    <%= form.number_field :month %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/credit_cards/edit.html.erb
<h1>Editing Credit Card</h1>

<%= render 'form', credit_card: @credit_card %>

<%= link_to 'Show', @credit_card %> |
<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Credit Cards</h1>

<table>
  <thead>
    <tr>
      <th>Digits</th>
      <th>Cvc</th>
      <th>Month</th>
      <th>Year</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credit_cards.each do |credit_card| %>
      <tr>
        <td><%= credit_card.digits %></td>
        <td><%= credit_card.cvc %></td>
        <td><%= credit_card.month %></td>
        <td><%= credit_card.year %></td>
        <td><%= credit_card.user %></td>
        <td><%= link_to 'Show', credit_card %></td>
        <td><%= link_to 'Edit', edit_credit_card_path(credit_card) %></td>
        <td><%= link_to 'Destroy', credit_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit Card', new_credit_card_path %>

app/views/credit_cards/new.html.erb
<h1>New Credit Card</h1>

<%= render 'form', credit_card: @credit_card %>

<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Digits:</strong>
  <%= @credit_card.digits %>
</p>

<p>
  <strong>Cvc:</strong>
  <%= @credit_card.cvc %>
</p>

<p>
  <strong>Month:</strong>
  <%= @credit_card.month %>
</p>

<p>
  <strong>Year:</strong>
  <%= @credit_card.year %>
</p>

<p>
  <strong>User:</strong>
  <%= @credit_card.user %>
</p>

<%= link_to 'Edit', edit_credit_card_path(@credit_card) %> |
<%= link_to 'Back', credit_cards_path %>