config/routes.rb
Rails.application.routes.draw do
  resources :credit_cards
 
  devise_for :users
 
  resources :products
  resources :charges
  get 'charges/:id/paypal_payment', to: 'charges#paypal_payment', as: 'paypal_payment'
  match '/paypal_action' => 'charges#paypal_action', via: [:get, :post], as: 'paypal_action'
  match '/payu_callback' => 'charges#payu_return', via: [:get, :post], as: 'payments_payu_return'

  mount StripeEvent::Engine, at: '/payments'
  root to: 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_card_and_charge_form.html.erb
<%= form_for current_user.credit_cards.new, url: charges_path do |f| %>
  <%= hidden_field_tag :product_id, product.id %>
 
  <%= render 'shared/form_errors', f: @card if @card.present? %>
 
  <%= f.text_field :digits, placeholder: 'Card number' %>
  <%= f.text_field :month, placeholder: 'Expired month'  %>
  <%= f.text_field :year, placeholder: 'Expired year'  %>
  <%= f.text_field :cvc, placeholder: 'CVC'  %>
 
  <%= f.button :submit, data: { 'disable-with' => 'Please wait ...' }  %>
<% end %>

app/views/shared/_charge_form.html.erb
<%= form_for :charge, url: charges_path do |f| %>
  <%= hidden_field_tag :product_id, product.id %>
 
  <% if flash[:error].present? %>
    <p><%= flash[:error] %></p>
  <% end %>
 
  <%= f.select :card_id, current_user.credit_cards.reject{ |card| card.new_record? }.collect { |card| [card.digits, card.stripe_id] }, { include_blank: false } %>
  <%= f.button :submit, data: { 'disable-with' => 'Please wait ...' } %>
<% end %>